Launchpad/feature/t bot help components
Altalogy/tari pull request #183
Opened 2022-05-18 14:17 UTC by corquaid

Description
---

Motivation and Context
---
#44 
How Has This Been Tested?
---

2022-05-19 13:16 UTC, tomaszantas requested changes

2022-05-19 13:16 UTC, tomaszantas commented on applications/launchpad/gui-react/src/components/TBot/HelpComponents/styles.ts
> +  margin-bottom: 24px;
NIT: You may consider switching here to:

```
margin-bottom: `${({ theme }) => theme.spacingVertical(2)`;
```

2022-05-19 13:16 UTC, tomaszantas commented on applications/launchpad/gui-react/src/App.tsx
> +  const tbotQueue = useAppSelector(selectTBotQueue)
Move `useAppSelector(selectTBotQueue)` selector to the `TBotManager`, so it won't re-render whole App.tsx

2022-05-19 13:16 UTC, tomaszantas commented on applications/launchpad/gui-react/src/TBotManager.tsx
> +const ComponentMap: { [key: string]: React.FC } = {
I think that it may become quite large in the future, so maybe we can move this to the another file...

Also, you can move `TBotManager.tsx` along with the test to the `src/containers/TBot/*`.

2022-05-19 13:18 UTC, corquaid commented on applications/launchpad/gui-react/src/components/TBot/HelpComponents/styles.ts
> +  margin-bottom: 24px;
Done

2022-05-19 13:36 UTC, corquaid commented on applications/launchpad/gui-react/src/App.tsx
> +  const tbotQueue = useAppSelector(selectTBotQueue)
Fixed, but will refactor to `container` > `component` format anyway.

2022-05-19 14:29 UTC, corquaid commented on applications/launchpad/gui-react/src/TBotManager.tsx
> +const ComponentMap: { [key: string]: React.FC } = {
Done

2022-05-20 08:11 UTC, tomaszantas approved these changes
LGTM!

2022-05-20 08:38 UTC, merged