Description
Altalogy/tari pull request #280
Opened 2022-06-15 13:39 UTC by alex1307

The consistent naming convention should be used for tauri events.
The pattern is tari://{} or tari://{}_{}.

Motivation and Context
To avoid any confusion the naming must be consistent.

How Has This Been Tested?
It will be tested along with the front-end.

2022-06-15 21:06 UTC, CjS77 approved these changes
+1

2022-06-16 08:36 UTC, tarnas14 approved these changes

2022-06-16 08:37 UTC, tarnas14 commented
@alex1307 you need to remake this with signed commit, I think

2022-06-16 08:37 UTC, tarnas14 requested changes
commit unsigned, can't merge

2022-06-17 16:17 UTC, CjS77 commented
It's one line. I'll do it. Can't wait forever.

2022-06-17 16:17 UTC, closed without merging