feat: wallet recent transactions
Altalogy/tari pull request #361
Opened 2022-07-01 15:53 UTC by tomaszantas

Description
---

Motivation and Context
---

How Has This Been Tested?
---

2022-07-07 19:58 UTC, corquaid commented on applications/launchpad/gui-react/src/components/TransactionsList/index.tsx
> +const addNth = (day: number) => {
stealing this

2022-07-07 20:01 UTC, corquaid commented on applications/launchpad/gui-react/src/containers/WalletContainer/RecentTransactions/index.tsx
> +  const [currentPage, setCurrentPage] = useState(0)
just a question: why type some state variables and not all? What's the convention?

2022-07-07 20:06 UTC, corquaid commented on applications/launchpad/gui-react/src/useWalletEvents.ts
> +  Unknwon = 'unknown',
```suggestion
  Unknown = 'unknown',
```

2022-07-07 20:08 UTC, corquaid requested changes
Single typo and some comments, looks fine to me otherwise.

2022-07-08 08:16 UTC, tomaszantas commented on applications/launchpad/gui-react/src/containers/WalletContainer/RecentTransactions/index.tsx
> +  const [currentPage, setCurrentPage] = useState(0)
You are right, the `<number>` for total is redundant here.
The convention is that we don't have to declare type if the initial value in `useState()` defines it.
For instance, when we use primitives like number or string, we not necessary have to do that, for example:

```
const [a, setA] = useState('')
const [a, setA] = useState(1)
```

2022-07-08 09:31 UTC, corquaid approved these changes
LGTM!

2022-07-08 10:10 UTC, merged