Launchpad/readme/eslint
Altalogy/tari pull request #79
Opened 2022-04-20 11:34 UTC by tarnas14

Description
---

- add curly braces eslint rule for consistency
- add developer rules to readme.md 

Motivation and Context
---

this is for our development to be more streamlined and consistent, so that the code looks similar across the codebase

How Has This Been Tested?
---

n/a

2022-04-20 11:55 UTC, tomaszantas approved these changes, later dismissed
LGTM!

2022-04-20 13:46 UTC, tarnas14 commented
@corquaid this is a team-level change/agreement, could you also skim through this PR and add your approval if you find it worthy? :D

2022-04-20 14:15 UTC, corquaid submitted a review, later dismissed
LGTM!

2022-04-20 14:36 UTC, tomaszantas requested changes
One comment

2022-04-20 14:36 UTC, tomaszantas commented on applications/launchpad_v2/README.md
> +const TariButton = ({ onClick }: TariButtonProps) => { ... }
```suggestion
const TariButton = ({ onClick, color }: TariButtonProps) => { ... }
```

2022-04-20 14:36 UTC, tomaszantas commented on applications/launchpad_v2/README.md
> +const TariButton = ({ onClick }: TariButtonProps) => { ... }
Since the `color` is in the JSDoc, then it's good to have it also in the props

2022-04-21 08:12 UTC, tomaszantas approved these changes

2022-04-21 08:12 UTC, merged